### ISSUE TITLE
Incremental backup fails when --delete-wal is ran before incremental backup

### ISSUE THREAD

**Issue by gokulgurumurthy-alation** [postgrespro/pg_probackup#451] opened 2021-11-03 13:55 UTC
Steps to reproduce

1) Run a full backup

sudo -u postgres pg_probackup-13 backup -B /data2/backup/pgbackup --instance alation -h /tmp -p 5432 -U alation -b FULL

2) Delete expired wal logs using --delete-wal
sudo pg_probackup-9.6 delete -B /data2/backup/pgbackup --instance alation --delete-wal

3) Run incremental backup

sudo -u postgres pg_probackup-13 backup -B /data2/backup/pgbackup --instance alation -h /tmp -p 5432 -U alation -b INCR

Error:
'INFO: Backup start, pg_probackup version: 2.4.15, instance: alation, backup ID: R1JL37, backup mode: PAGE, wal mode: ARCHIVE, remote: false, compress-algorithm: none, compress-level: 1\n', "WARNING: This PostgreSQL instance was initialized without data block checksums. pg_probackup have no way to detect data block corruption without them. Reinitialize PGDATA with option '--data-checksums'.\n", 'WARNING: Current PostgreSQL role is superuser. It is not recommended to run backup or checkdb as superuser.\n', 'INFO: wait for pg_start_backup()\n', 'INFO: Parent backup: R1JL16\n', 'INFO: Wait for WAL segment /data2/backup/pgbackup/wal/alation/00000001000000000000006D to be archived\n', 'INFO: PGDATA size: 223MB\n', 'INFO: Extracting pagemap of changed blocks\n', 'WARNING: Thread [1]: Could not read WAL record at 0/6B0000A0: invalid record length at 0/6B0000A0: wanted 24, got 0\n', 'ERROR: Thread [1]: Possible WAL corruption. Error has occured during reading WAL segment "/data2/backup/pgbackup/wal/alation/00000001000000000000006B"\n', 'ERROR: Pagemap extraction failed, time elasped: 0 sec\n',

**Comment by gsmol** [comment] 2021-11-03 15:27
Hello!
Looks like a bug to me, I will try to reproduce it and return with conclusion shortly.
Thank you for a feedback!

**Comment by gsmol** [comment] 2021-11-03 15:42
Looks ok to me:
```
$ python3 -m unittest -v tests.delete.DeleteTest.test_issue_451
test_issue_451 (tests.delete.DeleteTest)
delete increment and all after him ... ['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup init -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/backup']
['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup add-instance --instance=node -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/backup -D /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/node/data']
['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup backup -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/backup --instance=node -p 14421 -d postgres -b full --no-sync']
['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup delete -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/backup --instance=node --delete-wal']
['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup backup -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/delete/test_issue_451/backup --instance=node -p 14421 -d postgres -b page --no-sync']
ok

----------------------------------------------------------------------
Ran 1 test in 4.871s

OK
```

Are you reliable reproducing it?

**Comment by gsmol** [comment] 2021-11-03 15:43
Is it possible to obtain verbose log for your case (with `--log-level-file=verbose`)?

**Comment by gsmol** [comment] 2021-11-03 15:44
Out of `pg_probackup-13 show -B /data2/backup/pgbackup --instance alation`  and `pg_probackup-13 show -B /data2/backup/pgbackup --instance alation --archive` also would be nice to have.

**Comment by MetalDream666** [comment] 2022-07-12 09:44
The problem can't be reproduced. Closing the issue for now. @gokulgurumurthy-alation, if problem is still actual, please describe it in more detail (see messages from @gsmol)

**Closed by MetalDream666** 2022-07-12 09:44 UTC
Labels: bug
