### ISSUE TITLE
pg 10 make 2.0.2

### ISSUE THREAD

**Issue by longtian001** [postgrespro/pg_probackup#18] opened 2017-08-28 10:22 UTC
src/dir.c: In function ‘get_control_value’:
src/dir.c:799:21: warning: ‘buf_uint64_ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       buf_uint64_ptr++;

**Comment by longtian001** [comment] 2017-08-28 10:24
postgresql-10beta3

make show above,normal is no  "warning"

**Comment by longtian001** [comment] 2017-08-29 01:48
OS: CentOS Linux release 7.3.1611 (Core)  X64

I do somethine as following(as root user):
tar zxvf postgresql-10beta3.tar.gz
cp pg_probackup-2.0.2.tar.gz  postgresql-10beta3/contrib/
cd postgresql-10beta3/contrib/
tar zxvf pg_probackup-2.0.2.tar.gz
mv pg_probackup-2.0.2 pg_probackup
cd ../
./configure --prefix=/opt/pgsql/10.0.b3
make
make install
cd contrib/pg_probackup
make

then display warning above

src/dir.c: In function ‘get_control_value’:
src/dir.c:799:21: warning: ‘buf_uint64_ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
buf_uint64_ptr++;

I'm not sure  if it affects pg_probackup normal  is used,Thank you.

**Comment by za-arthur** [comment] 2017-08-29 09:40
Thank you for the issue!
You can ignore this warning. It is not a bug. But I will fix the code to make compiler quiet a little bit later.

**Comment by za-arthur** [comment] 2017-09-01 07:57
Fixed, check please.

**Comment by longtian001** [comment] 2017-09-03 01:35
Hi,za-arthur
there is no warning appear,thank you.

test result as following:

[root@masterdb postgresql-10beta4]# cd contrib/
[root@masterdb contrib]# cd pg_probackup/
[root@masterdb pg_probackup]# make
rm -f src/datapagemap.h && ln -s ../../../src/bin/pg_rewind/datapagemap.h src/datapagemap.h
rm -f src/logging.h && ln -s ../../../src/bin/pg_rewind/logging.h src/logging.h
rm -f src/receivelog.h && ln -s ../../../src/bin/pg_basebackup/receivelog.h src/receivelog.h
rm -f src/streamutil.h && ln -s ../../../src/bin/pg_basebackup/streamutil.h src/streamutil.h
rm -f src/walmethods.h && ln -s ../../../src/bin/pg_basebackup/walmethods.h src/walmethods.h
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/backup.o src/backup.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/catalog.o src/catalog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/configure.o src/configure.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/data.o src/data.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/delete.o src/delete.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/dir.o src/dir.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/fetch.o src/fetch.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/help.o src/help.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/init.o src/init.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/pg_probackup.o src/pg_probackup.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/restore.o src/restore.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/show.o src/show.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/status.o src/status.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/util.o src/util.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/validate.o src/validate.c
rm -f src/datapagemap.c && ln -s ../../../src/bin/pg_rewind/datapagemap.c src/datapagemap.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/datapagemap.o src/datapagemap.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/parsexlog.o src/parsexlog.c
rm -f src/xlogreader.c && ln -s ../../../src/backend/access/transam/xlogreader.c src/xlogreader.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/xlogreader.o src/xlogreader.c
rm -f src/streamutil.c && ln -s ../../../src/bin/pg_basebackup/streamutil.c src/streamutil.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/streamutil.o src/streamutil.c
rm -f src/receivelog.c && ln -s ../../../src/bin/pg_basebackup/receivelog.c src/receivelog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/receivelog.o src/receivelog.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/archive.o src/archive.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/parray.o src/utils/parray.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/pgut.o src/utils/pgut.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/utils/logger.o src/utils/logger.c
rm -f src/walmethods.c && ln -s ../../../src/bin/pg_basebackup/walmethods.c src/walmethods.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -DFRONTEND -I. -I. -I../../src/include  -D_GNU_SOURCE  -I../../src/interfaces/libpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -Isrc  -c -o src/walmethods.o src/walmethods.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 src/backup.o src/catalog.o src/configure.o src/data.o src/delete.o src/dir.o src/fetch.o src/help.o src/init.o src/pg_probackup.o src/restore.o src/show.o src/status.o src/util.o src/validate.o src/datapagemap.o src/parsexlog.o src/xlogreader.o src/streamutil.o src/receivelog.o src/archive.o src/utils/parray.o src/utils/pgut.o src/utils/logger.o src/walmethods.o -L../../src/common -lpgcommon -L../../src/port -lpgport -L../../src/interfaces/libpq -lpq -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS -L../../src/port -L../../src/common -Wl,--as-needed -Wl,-rpath,'/opt/pgsql/10.0/lib',--enable-new-dtags  -lpgcommon -lpgport -lpthread -lz -lreadline -lrt -lcrypt -ldl -lm  -o pg_probackup
[root@masterdb pg_probackup]# make install
/usr/bin/mkdir -p '/opt/pgsql/10.0/bin'
/usr/bin/install -c  pg_probackup '/opt/pgsql/10.0/bin'
[root@masterdb pg_probackup]#

**Comment by longtian001** [comment] 2017-09-03 01:36
you can close this issue.

**Comment by za-arthur** [comment] 2017-09-03 06:57
Great! I close the issue.

**Closed by za-arthur** 2017-09-03 06:57 UTC
Labels: bug
